# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_4624',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('domain', models.CharField(max_length=200)),
                ('logontype', models.CharField(max_length=200)),
                ('sourcehost', models.CharField(max_length=200)),
                ('processname', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event_4625',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('domain', models.CharField(max_length=200)),
                ('logontype', models.CharField(max_length=200)),
                ('sourcehost', models.CharField(max_length=200)),
                ('processname', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=200)),
                ('substatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event_4672',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('privilegelist', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Event_4688',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event_4698',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event_4776',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('procname', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event_5140',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sharename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event_7045',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FA_imagepath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagepath', models.CharField(max_length=10000)),
                ('count', models.IntegerField(default=0)),
                ('characterscount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('total_succ_auths', models.IntegerField(default=0)),
                ('total_failed_auths', models.IntegerField(default=0)),
                ('unique_succ_remote_users', models.IntegerField(default=0)),
                ('unique_succ_local_users', models.IntegerField(default=0)),
                ('unique_failed_remote_users', models.IntegerField(default=0)),
                ('unique_failed_local_users', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleLmSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('delta', models.CharField(max_length=50, null=True)),
                ('hosts', models.CharField(max_length=3, null=True)),
                ('users', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=1000)),
                ('imagepath', models.CharField(max_length=10000)),
                ('servicetype', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('ngramscore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SourceIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceip', models.CharField(blank=True, max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('total_succ_auths', models.IntegerField(default=0)),
                ('total_failed_auths', models.IntegerField(default=0)),
                ('unique_succ_remote_hosts', models.IntegerField(default=0)),
                ('unique_failed_remote_hosts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousSourceBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.SourceIp')),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousUserBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=1000)),
                ('imagepath', models.CharField(max_length=10000)),
                ('arguments', models.CharField(max_length=10000)),
                ('count', models.IntegerField(default=0)),
                ('ngramscore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('succ_auth_events', models.IntegerField(default=0)),
                ('failed_auth_events', models.IntegerField(default=0)),
                ('unique_succ_local_hosts', models.IntegerField(default=0)),
                ('unique_succ_remote_hosts', models.IntegerField(default=0)),
                ('unique_failed_remote_hosts', models.IntegerField(default=0)),
                ('unique_succ_rdp_hosts', models.IntegerField(default=0)),
                ('unique_succ_network_hosts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WmiEvent_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('operationid', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=1000)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host')),
            ],
        ),
        migrations.AddField(
            model_name='suspicioususerbehavior',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.User'),
        ),
        migrations.AddField(
            model_name='possiblelm',
            name='attack_progression',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='Oriana.PossibleLmSession'),
        ),
        migrations.AddField(
            model_name='possiblelm',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Event_4624'),
        ),
        migrations.AddField(
            model_name='possiblelm',
            name='event_4698',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Oriana.Event_4698'),
        ),
        migrations.AddField(
            model_name='possiblelm',
            name='event_7045',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Oriana.Event_7045'),
        ),
        migrations.AddField(
            model_name='possiblelm',
            name='event_wmi_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Oriana.WmiEvent_2'),
        ),
        migrations.AddField(
            model_name='event_7045',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host'),
        ),
        migrations.AddField(
            model_name='event_7045',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Service'),
        ),
        migrations.AddField(
            model_name='event_5140',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host'),
        ),
        migrations.AddField(
            model_name='event_5140',
            name='sourceip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Oriana.SourceIp'),
        ),
        migrations.AddField(
            model_name='event_5140',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.User'),
        ),
        migrations.AddField(
            model_name='event_4776',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host'),
        ),
        migrations.AddField(
            model_name='event_4776',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.User'),
        ),
        migrations.AddField(
            model_name='event_4698',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host'),
        ),
        migrations.AddField(
            model_name='event_4698',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Task'),
        ),
        migrations.AddField(
            model_name='event_4688',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host'),
        ),
        migrations.AddField(
            model_name='event_4688',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.User'),
        ),
        migrations.AddField(
            model_name='event_4672',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host'),
        ),
        migrations.AddField(
            model_name='event_4672',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.User'),
        ),
        migrations.AddField(
            model_name='event_4625',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host'),
        ),
        migrations.AddField(
            model_name='event_4625',
            name='sourceip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Oriana.SourceIp'),
        ),
        migrations.AddField(
            model_name='event_4625',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.User'),
        ),
        migrations.AddField(
            model_name='event_4624',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.Host'),
        ),
        migrations.AddField(
            model_name='event_4624',
            name='sourceip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Oriana.SourceIp'),
        ),
        migrations.AddField(
            model_name='event_4624',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oriana.User'),
        ),
    ]
